const { REACT_APP_BASE_API, REACT_APP_LOGIN_API, REACT_APP_SCRAPER_API, REACT_APP_USER_REG_LIST_API, REACT_APP_USER_REG_SAVE_API } = process.env
console.log('REACT_APP_BASE_API>> ',REACT_APP_BASE_API)
export const apiEndpoints = {
    loginApi: `${REACT_APP_BASE_API}${REACT_APP_LOGIN_API}`,
    scraperApi: `${REACT_APP_BASE_API}${REACT_APP_SCRAPER_API}`,
    listRegUsersApi: `${REACT_APP_BASE_API}${REACT_APP_USER_REG_LIST_API}`,
    saveRegUsersApi: `${REACT_APP_BASE_API}${REACT_APP_USER_REG_SAVE_API}`,
}